__title__ = 'pyrtdb'
__description__ = 'Python connector for rtdb'
__url__ = ''
__version__ = '0.0.1.dev3'
__author__ = 'devrtdb'
__author_email__ = 'dev@rtdb.com'
__license__ = 'GNU Lesser General Public License v3 (LGPLv3)'
__copyright__ = 'Copyright 2022 RTDB'
